name: Bug Report
description: Report a bug in Malwar
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: A clear description of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Run `malwar scan ...`
        2. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What actually happened?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Malwar Version
      placeholder: "0.2.0"
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: "3.13"
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Ubuntu 24.04"
